name: CI

on: [ "push", "pull_request" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Environment Variables
        run: |
          echo "AmongUs=/path/to/AmongUs" >> $GITHUB_ENV
          echo "GamePlatform=Steam" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Run the Cake script
        run: dotnet cake build.cake --verbosity=Diagnostic

      - uses: actions/upload-artifact@v4
        with:
          name: Peasmod.dll
          path: Peasmod/bin/Release/netstandard2.1/Peasmod.dll
